# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(upload_to='comida/images/'),
        ),
    ]
