# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comida', '0002_auto_20171031_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida_id', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comida',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
