# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0003_auto_20171107_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='comida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida'),
        ),
    ]
