# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comida', '0004_auto_20171107_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='comidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('costo', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='comida/images/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='comida/images/')),
                ('tipo_usuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comida',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='created_date',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='comida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comidas'),
        ),
        migrations.DeleteModel(
            name='comida',
        ),
    ]
